#!/bin/bash

# Expects a local pandoc installation
pandoc=`which pandoc`
readme="README.md"
tmp=".tmp.md" # Temporary metadata for autogenerated README output

cat > $readme <<END
# 19th century utopian novels by women
A small collection of 19th/20th century utopian fiction.

This collection was part of the research material for the interactive fiction story, [Harmonia](https://github.com/lizadaly/harmonia).

The current collection:
END

for dir in books/*
  do
    book="$(basename "$dir")"

    echo "Generating HTML files for $book as $dir/$book.html"
    pandoc  -o $dir/$book.html $dir/book.md  --css ../../shared/web.css \
      --template shared/pandoc-template.html --resource-path $dir:shared

    pandoc  -o $tmp $dir/book.md -V book=$book -V dir=$dir --template shared/metadata-template.md
    cat $tmp >> $readme
    rm $tmp

    echo "Generating EPUB files for $book as $dir/$book.epub"
    pandoc -o $dir/$book.epub $dir/book.md --epub-embed-font=shared/fonts/* \
      --css shared/epub.css --epub-cover-image $dir/cover.png
  done
